# Generated by Django 5.2 on 2025-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slavasity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(verbose_name='Дата выпуска'),
        ),
    ]
