# Generated by Django 5.2 on 2025-04-30 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slavasity', '0004_game_developer_game_publisher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='slavasity.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список желаемого',
                'verbose_name_plural': 'Списки желаемого',
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
