# Generated by Django 5.2 on 2025-05-05 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slavasity', '0005_wishlist_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='login_address',
            field=models.TextField(blank=True, null=True, verbose_name='Логин аккаунта получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Кредитная карта'), ('online', 'Онлайн-платёж')], default='online', max_length=255, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Лицензионный ключ')),
                ('delivery_status', models.CharField(choices=[('processing', 'Обрабатывается'), ('sent', 'Отправлен'), ('delivered', 'Доставлен')], default='processing', max_length=255, verbose_name='Статус доставки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_order', to='slavasity.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Post-Order',
                'verbose_name_plural': 'Post-Orders',
            },
        ),
    ]
